package com.dropwizard.model;

import jakarta.validation.constraints.NotEmpty;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * Represents a conference session entity.
 * This model is used to map session data between the API, service, and database layers.
 */
@Data // Lombok annotation to generate getters, setters, toString, equals, and hashCode
@NoArgsConstructor // Lombok annotation to generate a no-argument constructor
@AllArgsConstructor // Lombok annotation to generate an all-argument constructor
public class Session {

    /**
     * Unique identifier for the session.
     * Typically auto-generated by the database.
     */
    private int id;

    /**
     * Title of the session.
     * Cannot be empty; validated using Jakarta Bean Validation.
     */
    @NotEmpty
    private String title;

    /**
     * Detailed description of what the session is about.
     * Cannot be empty.
     */
    @NotEmpty
    private String description;

    /**
     * Name of the speaker delivering the session.
     * Cannot be empty.
     */
    @NotEmpty
    private String speakerName;

    /**
     * URL pointing to a file uploaded for the session (e.g., PDF slides).
     * Cannot be empty.
     */
    @NotEmpty
    private String fileUploadUrl;
}
